name: styleman
description: "اپلیکیشن فروشگاهی استایل من"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# بخش تنظیمات آیکون (دقیقاً از ابتدای خط شروع شود)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.jpg"

flutter:
  uses-material-design: true

  # معرفی فایل عکس به فلاتر
  assets:
    - assets/app_icon.jpg